# Generated by Django 5.2.5 on 2025-08-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_tasklist_created_at_alter_tasklist_manage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
