# Generated by Django 5.2.5 on 2025-09-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0003_tasklist_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='manage',
            new_name='gestionnaire',
        ),
    ]
