# Generated by Django 5.2.5 on 2025-12-22 13:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0004_rename_manage_tasklist_gestionnaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklist',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_all_tasks', 'Can view all tasks (admin permission)')], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when task was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='done',
            field=models.BooleanField(default=False, help_text='Whether the task is completed', verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='gestionnaire',
            field=models.ForeignKey(help_text='User who owns this task', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='task',
            field=models.CharField(help_text='Description of the task (3-200 characters)', max_length=200, validators=[django.core.validators.MinLengthValidator(3, 'Task must be at least 3 characters long'), django.core.validators.MaxLengthValidator(200, 'Task cannot exceed 200 characters')], verbose_name='Task Description'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when task was last updated', verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='tasklist',
            index=models.Index(fields=['gestionnaire', 'done'], name='todolist_ap_gestion_11c05f_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklist',
            index=models.Index(fields=['created_at'], name='todolist_ap_created_f90256_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklist',
            index=models.Index(fields=['done'], name='todolist_ap_done_b83e9c_idx'),
        ),
    ]
